### PR TITLE
Issue 2

### PR DESCRIPTION
**Pull request by Brice1827**
Create function createMultiplePkNotId for cases when table pk is not 'id'

### CODE REVIEW

**Comment by mtangoo** [comment]
I will definitely go through the PR, but at the outset it seems like you have added completely new function doing the same thing, only a different PK name. If am correct, why not add pk attribute with default value 'id' so that we have same function

**Comment by Brice1827** [comment]
I wanted to keep the current way of working for uses already in progress, so as not to break anything (i.e. to avoid having to modify the controller).

**Comment by mtangoo** [comment]
>I wanted to keep the current way of working for uses already in progress

You can add third parameter name `pkeyName` or something which defaults to `'id'` which will not affect currently existing codebases

**Comment by Brice1827** [comment]
OK rejet PR, i will make another monday

**Comment by mtangoo** [comment]
You can do the changes and push a commit to same PR

**Review by mtangoo — APPROVED** [review]

**Comment by mtangoo** [comment]
I think all is well. Can you add a line on changelog before it can be merged?
Sorry for late reply.

**Comment by mtangoo** [comment]
@Brice1827 thanks for your time and efforts.

**Pull request merged**
